

import type { Metadata } from "next";
// Google font has been integrated, use preffered font
import { Poppins } from "next/font/google"; 
import "./globals.css";
import Header from "./Components/Header";

const poppins = Poppins({ 
      weight: ["400", "500", "600", "700", "800"],  
      subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Jane's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        {children}
      
      </body>
    </html>
  );
}
